# 1. Create a 3x3x3 array with random values 

In [3]:
import numpy as np

x=np.random.random((3*3*3))
print(x)

[0.2847221  0.91825799 0.87742507 0.33626769 0.24502749 0.67910221
 0.69053441 0.80825849 0.04941966 0.3730111  0.90212166 0.58836229
 0.60882979 0.47331079 0.30818641 0.86261982 0.83743954 0.74880009
 0.08378802 0.40589231 0.20491074 0.58742717 0.63883338 0.70057113
 0.06950998 0.51998078 0.17656579]


# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [10]:
import numpy as np
a1=np.array([[1,2,3,4],[1,2,3,4],[1,2,3,4],[1,2,3,4],[1,2,3,4]])
print(a1)

[[1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]]


# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [22]:
x = np.zeros((8,8),dtype=int)
x[1::2,::2] = 1
x[::2,1::2] = 1
print("The checkboard:" )
print(x)



The checkboard:
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# 4. Normalize a 5x5 random matrix

In [26]:
y=np.random.random((5,5))
print("The original array:")
print(y)
ymax,ymin=y.max(),y.min()
y = (y - ymin)/(ymax - ymin)
print("After Normalization:")
print(y)


The original array:
[[0.75251333 0.54875191 0.15706119 0.80448505 0.61542517]
 [0.1921986  0.28202801 0.74321518 0.56432533 0.56840373]
 [0.76417584 0.25524991 0.24069817 0.22639099 0.85405667]
 [0.75989257 0.22099078 0.35438447 0.61081835 0.5823474 ]
 [0.67766662 0.93574846 0.19270762 0.67722827 0.49961597]]
After Normalization:
[[0.76468714 0.50301416 0.         0.83142987 0.5886368 ]
 [0.0451239  0.16048396 0.75274634 0.52301374 0.52825127]
 [0.77966429 0.12609518 0.10740766 0.08903419 0.89509038]
 [0.77416366 0.08209917 0.25340504 0.58272066 0.54615791]
 [0.66856806 1.         0.04577759 0.66800511 0.43991316]]


# 5.  How to find common values between two arrays?

In [29]:
a1=np.array([0,101,12,23,343,67])
print("a1:",a1)
a2=np.array([0,101,12,23,656,8686,2,23,2436,])
print("a2",a2)
print("common value of a1 & a2:",np.intersect1d(a1,a2))

a1: [  0 101  12  23 343  67]
a2 [   0  101   12   23  656 8686    2   23 2436]
common value of a1 & a2: [  0  12  23 101]


# 6.How to get the dates of yesterday, today and tomorrow?

In [30]:
import numpy as np
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("Yestraday: ",yesterday)
today     = np.datetime64('today', 'D')
print("Today: ",today)
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Tomorrow: ",tomorrow)

Yestraday:  2020-07-24
Today:  2020-07-25
Tomorrow:  2020-07-26


# 7. Consider two random array A and B, check if they are equal

In [44]:

First_array = np.array([[1,2],[3,4]])
second_array = np.array([[1,2],[3,4]])

comparison = First_array == second_array
equal_arrays = comparison.all()

print(equal_arrays)

True


# 8.Create random vector of size 10 and replace the maximum value by 0 

In [47]:
x=np.random.random((10))
print("The original array:",x)
x[x.argmax()]=0
print("The max value of 10 is:")
print(x)

The original array: [0.27407956 0.06342412 0.54563925 0.77028349 0.31221993 0.88228252
 0.08976454 0.77893499 0.96476623 0.78925186]
The max value of 10 is:
[0.27407956 0.06342412 0.54563925 0.77028349 0.31221993 0.88228252
 0.08976454 0.77893499 0.         0.78925186]


# 9. How to print all the values of an array?

In [48]:
my_array = np.arange(100)
print(my_array)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


# 10.Subtract the mean of each row of a matrix

In [50]:
import numpy as np
print("Original matrix:\n")
X = np.random.rand(5, 10)
print(X)
print("\nSubtract the mean of each row of the said matrix:\n")
Y = X - X.mean(axis=1, keepdims=True)
print(y)

Original matrix:

[[0.12522537 0.48540763 0.0780183  0.52408481 0.97275325 0.70189171
  0.10174308 0.84034552 0.69597513 0.0585498 ]
 [0.33861688 0.08388202 0.97832993 0.36452375 0.92540471 0.18524502
  0.21456513 0.04928378 0.25164114 0.62770167]
 [0.032045   0.55717219 0.62979378 0.86282793 0.64151326 0.28324342
  0.7508197  0.22079252 0.5754092  0.20252639]
 [0.61436641 0.66600398 0.15397851 0.68137372 0.89386302 0.02964536
  0.54149487 0.08071656 0.08893586 0.83789028]
 [0.97568762 0.32382999 0.11112134 0.22012395 0.90134    0.66323565
  0.97199076 0.23039483 0.17146605 0.41059825]]

Subtract the mean of each row of the said matrix:

[[0.76468714 0.50301416 0.         0.83142987 0.5886368 ]
 [0.0451239  0.16048396 0.75274634 0.52301374 0.52825127]
 [0.77966429 0.12609518 0.10740766 0.08903419 0.89509038]
 [0.77416366 0.08209917 0.25340504 0.58272066 0.54615791]
 [0.66856806 1.         0.04577759 0.66800511 0.43991316]]


# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

# 12.How to get the diagonal of a dot product?

In [3]:
import numpy as np

product=np.dot(5,3)
print("Dot product of scalar value:",product)

vector1=2+3j
vector2=5+8j
product=np.dot(vector1,vector2)
print("Dot of product:",product)


Dot product of scalar value: 15
Dot of product: (-14+31j)


# 13.How to find the most frequent value in an array?

In [1]:
import math as mt 
  
def mostFrequent(arr, n): 
  
    
    Hash = dict() 
    for i in range(n): 
        if arr[i] in Hash.keys(): 
            Hash[arr[i]] += 1
        else: 
            Hash[arr[i]] = 1
  
   
    max_count = 0
    res = -1
    for i in Hash:  
        if (max_count < Hash[i]):  
            res = i 
            max_count = Hash[i] 
          
    return res 
  

arr = [ 1, 5, 2, 1, 3, 2, 1]  
n = len(arr) 
print(mostFrequent(arr, n))

1


# 14.How to get the n largest values of an array

In [4]:
import numpy as np
x = np.arange(10)
print("Original array:")
print(x)
np.random.shuffle(x)
n = 1
print (x[np.argsort(x)[-n:]])

Original array:
[0 1 2 3 4 5 6 7 8 9]
[9]


# 15.How to create a record array from a regular array?

In [5]:
import numpy as np
arra1 = np.array([("Yasemin Rayner", 88.5, 90),
                 ("Ayaana Mcnamara", 87, 99),
             ("Jody Preece", 85.5, 91)])
print("Original arrays:")
print(arra1)
print("\nRecord array;")
result = np.core.records.fromarrays(arra1.T,
                              names='col1, col2, col3',
                              formats = 'S80, f8, i8')
print(result)

Original arrays:
[['Yasemin Rayner' '88.5' '90']
 ['Ayaana Mcnamara' '87' '99']
 ['Jody Preece' '85.5' '91']]

Record array;
[(b'Yasemin Rayner', 88.5, 90) (b'Ayaana Mcnamara', 87. , 99)
 (b'Jody Preece', 85.5, 91)]
